# Generated by Django 3.2.9 on 2021-12-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0002_rename_make_make_name'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='makes.make'),
            preserve_default=False,
        ),
    ]
