# Generated by Django 3.2.9 on 2021-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_model_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
