# Generated by Django 3.2.9 on 2021-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='maxUsedPrice',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='minUsedPrice',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
