# Generated by Django 3.2.9 on 2021-12-01 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='bodyType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='dateAdded',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='engineCapacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='gearBox',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=500), default=None, size=None),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='registrationNumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='yearOfManufacture',
            field=models.IntegerField(default=None),
        ),
    ]
