# Generated by Django 3.2.9 on 2021-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registrationNumber',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
