# Generated by Django 3.2.9 on 2021-12-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0001_initial'),
        ('cars', '0004_alter_car_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makes.make'),
        ),
    ]
