# Generated by Django 3.2.9 on 2021-12-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0002_rename_make_make_name'),
        ('cars', '0006_alter_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makes.make'),
        ),
    ]
