# Generated by Django 3.2.9 on 2021-12-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='bodyType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='car',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engineCapacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuelType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gearBox',
        ),
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registrationNumber',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='car',
            name='yearOfManufacture',
        ),
    ]
