# Generated by Django 3.2.9 on 2021-12-02 11:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_model_make'),
        ('makes', '0002_rename_make_make_name'),
        ('cars', '0016_auto_20211202_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bodyType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='dateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='engineCapacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='fuelType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='gearBox',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=500), default=None, size=None),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makes.make'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, limit_choices_to={'make': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makes.make')}, on_delete=django.db.models.deletion.CASCADE, to='models.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='registrationNumber',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='yearOfManufacture',
            field=models.IntegerField(default=None),
        ),
    ]
