# Generated by Django 3.2.9 on 2021-12-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_model_make'),
        ('cars', '0017_auto_20211202_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model'),
        ),
    ]
