# Generated by Django 3.2.9 on 2021-12-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='bodyType',
        ),
    ]
