# Generated by Django 3.2.9 on 2021-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_remove_car_bodytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bodyType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default=None, max_length=100),
        ),
    ]
