# Generated by Django 3.2.9 on 2021-12-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20211202_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, '2 doors'), (3, '3 doors'), (4, '4 doors'), (5, '5 doors')], default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearBox',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(choices=[(2, '2 seats'), (4, '4 seats'), (5, '5 seats'), (7, '7 seats'), (8, '8 seats')], default=None),
        ),
    ]
