# Generated by Django 3.2.9 on 2021-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='modelVariation',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
