# Generated by Django 3.2.9 on 2021-12-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_car_modelvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gearBox',
            new_name='gearbox',
        ),
    ]
