# Generated by Django 3.2.9 on 2021-12-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_rename_gearbox_car_gearbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
