# Generated by Django 3.2.9 on 2021-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_remove_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registrationNumber',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
