# Generated by Django 3.2.9 on 2021-12-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='make',
            new_name='name',
        ),
    ]
