# Generated by Django 3.2.9 on 2021-12-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20211202_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
